=== boyannna/XML---Project/Part1/VeterinaryClinic.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT veterinary_clinic (staffs, manipulations, patients, owners)>
 <!ELEMENT staffs (staff+)>
   <!ELEMENT staff (name_s, last_name_s, phone_number_s, position, salary, email_s)>
     <!ATTLIST staff id ID #REQUIRED >
     <!ELEMENT name_s (#PCDATA)>
     <!ELEMENT last_name_s (#PCDATA)>
     <!ELEMENT phone_number_s (#PCDATA)>
     <!ELEMENT position (#PCDATA)>
     <!ELEMENT salary (#PCDATA)>
     <!ELEMENT email_s (#PCDATA)>
 <!ELEMENT manipulations (manipulation+)>
   <!ELEMENT manipulation (name_m, price, duration)>
     <!ATTLIST manipulation anesthesia (with|without) #IMPLIED>
     <!ELEMENT name_m (#PCDATA)>
     <!ELEMENT price (#PCDATA)>
     <!ELEMENT duration (#PCDATA)>
 <!ELEMENT patients (patient+)>
   <!ELEMENT patient (name_p, type, breed, gender, age, weight)>
     <!ATTLIST patient
          no_microchip ID #REQUIRED
          presence_of_castration (YES|NO) #IMPLIED>
     <!ELEMENT name_p (#PCDATA)>
     <!ELEMENT type (#PCDATA)>
     <!ELEMENT breed (#PCDATA)>
     <!ELEMENT gender (#PCDATA)>
     <!ELEMENT age (#PCDATA)>
     <!ELEMENT weight (#PCDATA)>
 <!ELEMENT owners (owner+)>
   <!ELEMENT owner (name_o, last_name_o, phone_number_o, region, email_o)>
     <!ATTLIST owner id ID #REQUIRED >
     <!ELEMENT name_o (#PCDATA)>
     <!ELEMENT last_name_o (#PCDATA)>
     <!ELEMENT phone_number_o (#PCDATA)>
     <!ELEMENT region (#PCDATA)>
     <!ELEMENT email_o (#PCDATA)>

=== boyannna/XML---Project/Part1/VeterinaryClinic_2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE veterinary_clinic SYSTEM "D:\УНИ\5 - Пети семестър\XML\XML\.idea\Homework 1\VeterinaryClinic.dtd">

<veterinary_clinic>
   <staffs>
       <staff id="S002">
           <name_s>Ивайло</name_s>
           <last_name_s>Василев</last_name_s>
           <phone_number_s>0881234568</phone_number_s>
           <position>Доктор</position>
           <salary>4000</salary>
           <email_s>i.vasilev@gmail.com</email_s>
       </staff>
   </staffs>
    <manipulations>
        <manipulation anesthesia="without">
            <name_m>Кръвни тестове</name_m>
            <price>30</price>
            <duration>45</duration>
        </manipulation>
    </manipulations>
    <patients>
        <patient no_microchip="MNO0001102"
                 presence_of_castration="NO">
            <name_p>Багира</name_p>
            <type>Котка</type>
            <breed>Европейска късокосместа</breed>
            <gender>Ж</gender>
            <age>3</age>
            <weight>4</weight>
        </patient>
    </patients>
    <owners>
        <owner id="O51345">
            <name_o>Иван</name_o>
            <last_name_o>Иванов</last_name_o>
            <phone_number_o>0881234563</phone_number_o>
            <region>Враца</region>
            <email_o>i.ivanoff@gmail.com</email_o>
        </owner>
    </owners>
</veterinary_clinic>

=== boyannna/XML---Project/Part3/VetClinHelper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE veterinary_clinic SYSTEM "VeterinaryClinic.dtd">

<veterinary_clinic>
    <staffs>
        <staff id="S001">
            <name_s>Владимир</name_s>
            <last_name_s>Йорданов</last_name_s>
            <phone_number_s>0881234567</phone_number_s>
            <position>Ортопед</position>
            <salary>5000</salary>
            <email_s>v.yordanov@gmail.com</email_s>
        </staff>
    </staffs>
    <manipulations>
        <manipulation anesthesia="with">
            <name_m>Рентгенография</name_m>
            <price>50</price>
            <duration>30</duration>
        </manipulation>
    </manipulations>
    <patients>
        <patient presence_of_castration="YES" no_microchip="MNO0000001">
            <name_p>Кай</name_p>
            <type>Куче</type>
            <breed>Хъски</breed>
            <gender>М</gender>
            <age>10</age>
            <weight>30</weight>
        </patient>
    </patients>
    <owners>
        <owner id="O00001">
            <name_o>Боянна-Ди</name_o>
            <last_name_o>Маринова</last_name_o>
            <phone_number_o>0881234566</phone_number_o>
            <region>Козлодуй</region>
            <email_o>b.marinova@gmail.com</email_o>
        </owner>
    </owners>
</veterinary_clinic>

=== boyannna/XML---Project/Part1/VeterinaryClinic_3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE veterinary_clinic SYSTEM "D:\УНИ\5 - Пети семестър\XML\XML\.idea\Homework 1\VeterinaryClinic.dtd">

<veterinary_clinic>
   <staffs>
       <staff id="S003">
           <name_s>Йосиф</name_s>
           <last_name_s>Еленков</last_name_s>
           <phone_number_s>0881234569</phone_number_s>
           <position>Кардиолог</position>
           <salary>5000</salary>
           <email_s>j.elenkov@gmail.com</email_s>
       </staff>
   </staffs>
    <manipulations>
        <manipulation anesthesia="without">
            <name_m>Електрокардиограма</name_m>
            <price>45</price>
            <duration>40</duration>
        </manipulation>
    </manipulations>
    <patients>
        <patient no_microchip="MNO0000021"
                 presence_of_castration="YES">
            <name_p>Рикардо</name_p>
            <type>Котка</type>
            <breed>Европейска късокосместа</breed>
            <gender>М</gender>
            <age>10</age>
            <weight>6</weight>
        </patient>
    </patients>
    <owners>
        <owner id="O00021">
            <name_o>Иво</name_o>
            <last_name_o>Марков</last_name_o>
            <phone_number_o>0881234521</phone_number_o>
            <region>София</region>
            <email_o>i.markov@gmail.com</email_o>
        </owner>
    </owners>
</veterinary_clinic>

=== boyannna/XML---Project/Part1/VeterinaryClinic_5.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE veterinary_clinic SYSTEM "D:\УНИ\5 - Пети семестър\XML\XML\.idea\Homework 1\VeterinaryClinic.dtd">

<veterinary_clinic>
    <staffs>
        <staff id="S005">
            <name_s>Маргарита</name_s>
            <last_name_s>Илиева</last_name_s>
            <phone_number_s>0881234511</phone_number_s>
            <position>Хирург</position>
            <salary>5000</salary>
            <email_s>m.ilieva@gmail.com</email_s>
        </staff>
    </staffs>
    <manipulations>
        <manipulation anesthesia="with">
            <name_m>Кастрация</name_m>
            <price>120</price>
            <duration>60</duration>
        </manipulation>
    </manipulations>
    <patients>
        <patient no_microchip="MNO0983022"
                 presence_of_castration="NO">
            <name_p>Спайк</name_p>
            <type>Куче</type>
            <breed>Английски булдог</breed>
            <gender>М</gender>
            <age>2</age>
            <weight>21</weight>
        </patient>
    </patients>
    <owners>
        <owner id="O15821">
            <name_o>Диана</name_o>
            <last_name_o>Георгиева</last_name_o>
            <phone_number_o>0881233577</phone_number_o>
            <region>София</region>
            <email_o>d.georgieva@gmail.com</email_o>
        </owner>
    </owners>
</veterinary_clinic>

=== boyannna/XML---Project/Part1/VeterinaryClinic_4.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE veterinary_clinic SYSTEM "D:\УНИ\5 - Пети семестър\XML\XML\.idea\Homework 1\VeterinaryClinic.dtd">

<veterinary_clinic>
    <staffs>
        <staff id="S004">
            <name_s>Валя</name_s>
            <last_name_s>Митова</last_name_s>
            <phone_number_s>0881234560</phone_number_s>
            <position>Доктор</position>
            <salary>3000</salary>
            <email_s>v.mitova@gmail.com</email_s>
        </staff>
    </staffs>
    <manipulations>
        <manipulation anesthesia="with">
            <name_m>Грууминг</name_m>
            <price>60</price>
            <duration>60</duration>
        </manipulation>
    </manipulations>
    <patients>
        <patient no_microchip="MNO0023021"
                 presence_of_castration="NO">
            <name_p>Белла</name_p>
            <type>Котка</type>
            <breed>Персийска</breed>
            <gender>Ж</gender>
            <age>3</age>
            <weight>6</weight>
        </patient>
    </patients>
    <owners>
        <owner id="O04821">
            <name_o>Марио</name_o>
            <last_name_o>Николов</last_name_o>
            <phone_number_o>0881234571</phone_number_o>
            <region>Враца</region>
            <email_o>m.nikolov@gmail.com</email_o>
        </owner>
    </owners>
</veterinary_clinic>
